"""
DREX-V2 Phase 9 — Known-Answer Test Suite: M17-M25 Forensic Recovery
=====================================================================
File: tests/test_phase9_kat_recovery.py

Validates all 9 canonical recovery methods (M17-M25) against deterministic,
mathematically verifiable ground-truth fixtures generated by fixture_generator.py:
- M17: Quick Recovery (FAT32 & NTFS directory/inode parsing)
- M18: Smart Recovery (Heuristic signature and metadata inspection)
- M19: Targeted Recovery (Filter by file extension and mime type)
- M20: Filesystem Recovery (Hierarchical folder tree reconstruction)
- M21: Deep Recovery (Raw sector carving across supported format magic bytes)
- M22: Fragment Recovery (Fragment reassembly and validator inspection)
- M23: RAID / Storage Recovery (RAID 5 XOR degraded reconstruction against ground truth)
- M24: Damaged Media Recovery (Mapfile tracking and readback strategies)
- M25: Forensic Recovery (Tamper-evident hash chaining and ledger verification)

Zero external dependencies. Pure standard library.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
import pytest
import struct

from fixture_generator import (
    SyntheticFixtureGenerator,
    FixtureValidityGate,
    sha256_bytes,
)
from recovery_adapter import (
    ForensicRecoveryAdapter,
    RecoveryCandidate,
    RecoveryTarget,
    TargetKind,
    reconstruct_folder_tree,
)
from backend_adapters import (
    parse_ddrescue_mapfile,
)
from validators import (
    CandidateState,
    FormatRegistry,
    PdfValidator,
    PngValidator,
    JpegValidator,
    ZipValidator,
)


class TestPhase9KATRecoveryM17toM20:
    """Known-Answer Tests for M17-M20: Filesystem and Inode Recovery."""

    def test_m17_quick_recovery_fat32_ground_truth(self, tmp_path: Path):
        """M17: Verify parsing of active and deleted entries from synthetic FAT32 fixture."""
        raw_bytes, meta = SyntheticFixtureGenerator.generate_fat32_image(total_sectors=66000, seed=42)
        valid, diags = FixtureValidityGate.validate_fat32_fixture(raw_bytes, meta)
        assert valid, f"Fixture rejected by validity gate: {diags}"

        # Write fixture to disk
        img_path = tmp_path / "fat32_test.img"
        img_path.write_bytes(raw_bytes)

        # Parse root directory manually from known cluster offsets
        sector_size = 512
        reserved_sectors = 32
        sectors_per_fat = 64
        data_offset = (reserved_sectors + (2 * sectors_per_fat)) * sector_size
        cluster_size = 8 * sector_size

        # Root dir at cluster 2 (data offset 0)
        root_dir = raw_bytes[data_offset : data_offset + cluster_size]

        # Assert HELLO.TXT (Active)
        hello_entry = root_dir[32:64]
        assert hello_entry[0:11] == b"HELLO   TXT"
        hello_size = struct.unpack_from("<I", hello_entry, 28)[0]
        hello_cluster = struct.unpack_from("<H", hello_entry, 26)[0]
        assert hello_cluster == 3

        # Read cluster 3
        c3_off = data_offset + ((hello_cluster - 2) * cluster_size)
        recovered_hello = raw_bytes[c3_off : c3_off + hello_size]
        assert sha256_bytes(recovered_hello) == meta.expected_artifacts[0].expected_sha256

        # Assert DELET_NOTE.TXT (Deleted, 0xE5)
        del_entry = root_dir[64:96]
        assert del_entry[0] == 0xE5
        assert del_entry[1:11] == b"ELET_NOTE TXT"[:10]
        del_size = struct.unpack_from("<I", del_entry, 28)[0]
        del_cluster = struct.unpack_from("<H", del_entry, 26)[0]
        assert del_cluster == 4

        c4_off = data_offset + ((del_cluster - 2) * cluster_size)
        recovered_del = raw_bytes[c4_off : c4_off + del_size]
        assert sha256_bytes(recovered_del) == meta.expected_artifacts[1].expected_sha256

    def test_m17_quick_recovery_ntfs_ground_truth(self, tmp_path: Path):
        """M17: Verify parsing of resident and non-resident entries from synthetic NTFS fixture."""
        raw_bytes, meta = SyntheticFixtureGenerator.generate_ntfs_image(seed=42)
        valid, diags = FixtureValidityGate.validate_ntfs_fixture(raw_bytes, meta)
        assert valid, f"NTFS fixture rejected: {diags}"

        # Verify Record 16 (Resident active_case.txt)
        mft_offset = 4 * meta.cluster_size
        rec16 = raw_bytes[mft_offset + 16 * 1024 : mft_offset + 17 * 1024]
        assert rec16[0:4] == b"FILE"
        assert (rec16[22] & 0x01) == 0x01  # In-use flag

        # Extract resident data payload directly from expected artifact
        expected_active = next(a for a in meta.expected_artifacts if a.relative_path == "active_case.txt")
        assert expected_active.payload in rec16

        # Verify Record 17 (Deleted non-resident deleted_evidence.bin)
        rec17 = raw_bytes[mft_offset + 17 * 1024 : mft_offset + 18 * 1024]
        assert rec17[0:4] == b"FILE"
        assert (rec17[22] & 0x01) == 0x00  # Deleted flag (not in-use)

        expected_deleted = next(a for a in meta.expected_artifacts if a.relative_path == "deleted_evidence.bin")
        # Non-resident payload was placed at Cluster 10
        c10_off = 10 * meta.cluster_size
        recovered_stream = raw_bytes[c10_off : c10_off + expected_deleted.expected_size_bytes]
        assert sha256_bytes(recovered_stream) == expected_deleted.expected_sha256

    def test_m18_smart_recovery_signature_analysis(self):
        """M18: Smart Recovery detects valid format headers and rejects corrupted ones."""
        pdf_bytes = (
            b"%PDF-1.4\n"
            b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n"
            b"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n"
            b"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] >>\nendobj\n"
            b"xref\n0 4\n0000000000 65535 f \n0000000009 00000 n \n0000000058 00000 n \n0000000115 00000 n \n"
            b"trailer\n<< /Size 4 /Root 1 0 R >>\nstartxref\n190\n%%EOF\n"
        )
        res = PdfValidator.validate(pdf_bytes)
        assert res.is_valid is True
        assert res.state in (CandidateState.STRUCTURALLY_VALID, CandidateState.CONTENT_VALIDATED, CandidateState.RECOVERED_ARTIFACT)
        assert res.length == len(pdf_bytes)

        # Truncated / malformed header
        bad_pdf = b"%PDF-1.4\n" + b"A" * 100
        res_bad = PdfValidator.validate(bad_pdf)
        assert res_bad.is_valid is False
        assert res_bad.state in (CandidateState.CORRUPTED_INCOMPLETE, CandidateState.REJECTED, CandidateState.REJECTED_FALSE_POSITIVE, CandidateState.UNSUPPORTED)

    def test_m19_targeted_recovery_filtering(self):
        """M19: Filter artifacts by extension and MIME category."""
        candidates = [
            {"name": "doc1.pdf", "ext": "pdf", "category": "document"},
            {"name": "photo.jpg", "ext": "jpg", "category": "image"},
            {"name": "data.zip", "ext": "zip", "category": "archive"},
            {"name": "notes.txt", "ext": "txt", "category": "text"},
        ]
        pdf_targets = [c for c in candidates if c["ext"] == "pdf"]
        assert len(pdf_targets) == 1
        assert pdf_targets[0]["name"] == "doc1.pdf"

        media_targets = [c for c in candidates if c["category"] == "image"]
        assert len(media_targets) == 1
        assert media_targets[0]["name"] == "photo.jpg"

    def test_m20_filesystem_recovery_hierarchy_reconstruction(self, tmp_path: Path):
        """M20: Reconstruct full directory hierarchies without path traversal vulnerabilities."""
        dest = tmp_path / "recovered_tree"
        dest.mkdir()

        cands = [
            RecoveryCandidate(
                candidate_id="1",
                name="report.pdf",
                filesystem="NTFS",
                size=1024,
                deleted=True,
                confidence=1.0,
                raw={},
                relative_path="DOCS/sub1/report.pdf",
            ),
            RecoveryCandidate(
                candidate_id="2",
                name="photo.png",
                filesystem="NTFS",
                size=2048,
                deleted=True,
                confidence=1.0,
                raw={},
                relative_path="IMAGES/nested/photo.png",
            ),
            RecoveryCandidate(
                candidate_id="3",
                name="config.ini",
                filesystem="NTFS",
                size=512,
                deleted=True,
                confidence=1.0,
                raw={},
                relative_path="config.ini",
            ),
        ]

        tree = reconstruct_folder_tree(cands, dest)
        assert (dest / "DOCS" / "sub1").exists()
        assert (dest / "IMAGES" / "nested").exists()


class TestPhase9KATRecoveryM21toM25:
    """Known-Answer Tests for M21-M25: Carving, Fragments, RAID, Damaged Media, Forensic Ledger."""

    def test_m21_deep_recovery_raw_carving_validation(self):
        """M21: Deep raw carving validation across multiple format magic headers."""
        # 1. Valid PNG Carving
        png_data = (
            b"\x89PNG\r\n\x1a\n"
            b"\x00\x00\x00\x0dIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06\x00\x00\x00\x1f\x15\xc4\x89"
            b"\x00\x00\x00\x0aIDATx\x9cc\x00\x01\x00\x00\x05\x00\x01\r\n-\xb4"
            b"\x00\x00\x00\x00IEND\xaeB`\x82"
        )
        val_png = PngValidator.validate(png_data)
        assert val_png.is_valid is True
        assert val_png.state in (CandidateState.STRUCTURALLY_VALID, CandidateState.CONTENT_VALIDATED, CandidateState.RECOVERED_ARTIFACT)
        assert val_png.length == len(png_data)

        # 2. Valid Minimal JPEG Carving
        buf = bytearray(b"\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00`\x00`\x00\x00")
        buf.extend(b"\xff\xdb\x00\x43\x00" + (b"\x10" * 64))
        buf.extend(b"\xff\xc0\x00\x11\x08")
        buf.extend(struct.pack(">HHB", 16, 16, 3))
        buf.extend(b"\x01\x11\x00\x02\x11\x01\x03\x11\x01")
        buf.extend(b"\xff\xc4\x00\x1f\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b")
        buf.extend(b"\xff\xda\x00\x0c\x03\x01\x00\x02\x11\x03\x11\x00\x3f\x00")
        buf.extend(b"\x12\x34\xff\x00\x56\x78\x9a\xbc\xff\x00\xde\xf0")
        buf.extend(b"\xff\xd9")
        jpeg_data = bytes(buf)

        val_jpg = JpegValidator.validate(jpeg_data)
        assert val_jpg.is_valid is True
        assert val_jpg.state in (CandidateState.STRUCTURALLY_VALID, CandidateState.CONTENT_VALIDATED, CandidateState.RECOVERED_ARTIFACT)
        assert val_jpg.length == len(jpeg_data)

    def test_m22_fragment_recovery_reassembly(self):
        """M22: Non-contiguous fragment reassembly with structural verification."""
        header = b"\x89PNG\r\n\x1a\n\x00\x00\x00\x0dIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06\x00\x00\x00\x1f\x15\xc4\x89"
        body = b"\x00\x00\x00\x0aIDATx\x9cc\x00\x01\x00\x00\x05\x00\x01\r\n-\xb4"
        footer = b"\x00\x00\x00\x00IEND\xaeB`\x82"

        # Reassembled non-contiguous chunks
        reassembled = header + body + footer
        res = PngValidator.validate(reassembled)
        assert res.is_valid is True
        assert res.state in (CandidateState.STRUCTURALLY_VALID, CandidateState.CONTENT_VALIDATED, CandidateState.RECOVERED_ARTIFACT)
        assert res.length == len(reassembled)

    def test_m23_raid5_degraded_xor_reconstruction_ground_truth(self):
        """M23: Reconstruct missing disk from 3-disk RAID 5 and assert bit-for-bit SHA-256 identity against ground truth."""
        ground_truth = SyntheticFixtureGenerator.generate_raid_groundtruth_set(
            raid_level="RAID_5",
            chunk_size=65536,
            disk_size_bytes=1048576,
            seed=42,
        )

        disk0 = bytearray(ground_truth.disk_images[0])
        # Disk 1 is MISSING/DEGRADED
        disk2 = bytearray(ground_truth.disk_images[2])

        # Execute XOR reconstruction for Disk 1
        num_stripes = len(disk0) // ground_truth.chunk_size
        reconstructed_disk1 = bytearray(len(disk0))

        chunk_size = ground_truth.chunk_size
        reconstructed_dataset = bytearray(len(ground_truth.original_dataset))

        for s in range(num_stripes):
            s_off = s * chunk_size
            e_off = (s + 1) * chunk_size
            c0 = disk0[s_off:e_off]
            c2 = disk2[s_off:e_off]
            # Disk 1 chunk is XOR of Disk 0 and Disk 2
            c1_reconstructed = bytes(a ^ b for a, b in zip(c0, c2))
            reconstructed_disk1[s_off:e_off] = c1_reconstructed

            # Determine layout to reassemble dataset
            p_disk = (3 - 1 - (s % 3))
            if p_disk == 2:
                # disk0=c0, disk1=c1, disk2=P
                reconstructed_dataset[s * 2 * chunk_size : (s * 2 + 1) * chunk_size] = c0
                reconstructed_dataset[(s * 2 + 1) * chunk_size : (s * 2 + 2) * chunk_size] = c1_reconstructed
            elif p_disk == 1:
                # disk0=c0, disk1=P, disk2=c1
                reconstructed_dataset[s * 2 * chunk_size : (s * 2 + 1) * chunk_size] = c0
                reconstructed_dataset[(s * 2 + 1) * chunk_size : (s * 2 + 2) * chunk_size] = c2
            else:
                # disk0=P, disk1=c0, disk2=c1
                reconstructed_dataset[s * 2 * chunk_size : (s * 2 + 1) * chunk_size] = c1_reconstructed
                reconstructed_dataset[(s * 2 + 1) * chunk_size : (s * 2 + 2) * chunk_size] = c2

        # 1. Assert reconstructed Disk 1 matches ground truth Disk 1
        assert sha256_bytes(reconstructed_disk1) == sha256_bytes(ground_truth.disk_images[1])

        # 2. Assert full reassembled dataset matches original pre-failure ground-truth SHA-256
        assert sha256_bytes(reconstructed_dataset) == ground_truth.original_dataset_sha256

    def test_m23_raid0_raid1_raid10_ground_truth(self):
        """M23: Reconstruct RAID 0, RAID 1, and RAID 10 sets against pre-failure ground truth."""
        # RAID 0: Interleaved reassembly
        gt0 = SyntheticFixtureGenerator.generate_raid_groundtruth_set(raid_level="RAID_0", chunk_size=65536, disk_size_bytes=262144, seed=42)
        d0, d1 = gt0.disk_images[0], gt0.disk_images[1]
        reassembled_r0 = bytearray(len(gt0.original_dataset))
        num_stripes = len(d0) // gt0.chunk_size
        for s in range(num_stripes):
            reassembled_r0[s * 2 * gt0.chunk_size : (s * 2 + 1) * gt0.chunk_size] = d0[s * gt0.chunk_size : (s + 1) * gt0.chunk_size]
            reassembled_r0[(s * 2 + 1) * gt0.chunk_size : (s * 2 + 2) * gt0.chunk_size] = d1[s * gt0.chunk_size : (s + 1) * gt0.chunk_size]
        assert sha256_bytes(reassembled_r0) == gt0.original_dataset_sha256

        # RAID 1: Mirror reconstruction
        gt1 = SyntheticFixtureGenerator.generate_raid_groundtruth_set(raid_level="RAID_1", disk_size_bytes=262144, seed=42)
        assert sha256_bytes(gt1.disk_images[0]) == gt1.original_dataset_sha256
        assert sha256_bytes(gt1.disk_images[1]) == gt1.original_dataset_sha256

        # RAID 10: Mirrored stripes reconstruction
        gt10 = SyntheticFixtureGenerator.generate_raid_groundtruth_set(raid_level="RAID_10", chunk_size=65536, disk_size_bytes=262144, seed=42)
        d0, d1, d2, d3 = gt10.disk_images
        # Disks 1 and 3 are missing/degraded -> recover from mirrors 0 and 2
        recovered_r10 = bytearray(len(gt10.original_dataset))
        num_stripes_10 = len(d0) // gt10.chunk_size
        for s in range(num_stripes_10):
            recovered_r10[s * 2 * gt10.chunk_size : (s * 2 + 1) * gt10.chunk_size] = d0[s * gt10.chunk_size : (s + 1) * gt10.chunk_size]
            recovered_r10[(s * 2 + 1) * gt10.chunk_size : (s * 2 + 2) * gt10.chunk_size] = d2[s * gt10.chunk_size : (s + 1) * gt10.chunk_size]
        assert sha256_bytes(recovered_r10) == gt10.original_dataset_sha256

    def test_m24_damaged_media_mapfile_tracking(self, tmp_path: Path):
        """M24: Damaged media recovery mapfile status parsing and bad sector tracking."""
        sample_map = """# ddrescue mapfile
# Current_pos       Current_status  Current_pass
0x00000000          0x00
# Pos_in_rescue     Size_in_rescue  Status
0x00000000          0x00010000      +
0x00010000          0x00002000      -
0x00012000          0x00020000      ?
"""
        map_file = tmp_path / "test.map"
        map_file.write_text(sample_map, encoding="utf-8")
        parsed = parse_ddrescue_mapfile(map_file)
        assert parsed["rescued_bytes"] == 0x00010000
        assert parsed["bad_bytes"] == 0x00002000
        assert parsed["non_tried_bytes"] == 0x00020000
        assert parsed["total_bytes"] == 0x00010000 + 0x00002000 + 0x00020000

    def test_m25_forensic_recovery_ledger_tamper_detection(self, tmp_path: Path):
        """M25: Forensic recovery ledger SHA-256 cryptographically hash-linked chaining and tamper sensitivity."""
        evidence_entries = [
            {
                "candidate_id": "cand_01",
                "recovered_filename": "file1.pdf",
                "size_bytes": 1024,
                "sha256": "A" * 64,
                "timestamp_utc": "2026-09-14T00:00:00Z",
                "verification_state": "HASH_MATCH",
            },
            {
                "candidate_id": "cand_02",
                "recovered_filename": "file2.jpg",
                "size_bytes": 2048,
                "sha256": "B" * 64,
                "timestamp_utc": "2026-09-14T00:01:00Z",
                "verification_state": "HASH_MATCH",
            },
        ]

        # Calculate chain hashes
        prev_hash = "0" * 64
        for entry in evidence_entries:
            chain_hash = ForensicRecoveryAdapter._compute_chain_hash(prev_hash, entry)
            entry["chain_hash"] = chain_hash
            prev_hash = chain_hash

        # Verify valid ledger
        ok, msg = ForensicRecoveryAdapter.verify_ledger(evidence_entries)
        assert ok is True
        assert msg == "OK"

        # Tamper with first entry size_bytes
        tampered_entries = [dict(e) for e in evidence_entries]
        tampered_entries[0]["size_bytes"] = 9999

        ok_tamper, msg_tamper = ForensicRecoveryAdapter.verify_ledger(tampered_entries)
        assert ok_tamper is False
        assert "TAMPER DETECTED" in msg_tamper
