"""Tests for DREX-V2 Phase 5 Damaged Media Acquisition & Mapfile Architecture
========================================================================
Validates clean-room GNU ddrescue mapfile model, multi-pass merge logic,
resumable sector-level imaging, read-only source immutability, and CLI adapters.
"""

import hashlib
import tempfile
from pathlib import Path
import pytest

from damaged_media import DdrescueMapfile, MapBlockStatus, MapfileBlock
from recovery_adapter import DirectDamagedMediaImager
from backend_adapters import build_ddrescue_command, parse_ddrescue_output


class TestDdrescueMapfileModel:
    """Validate clean-room GNU ddrescue mapfile parser, serializer, and merge engine."""

    SAMPLE_MAPFILE_TEXT = (
        "# Mapfile generated by GNU ddrescue version 1.28\n"
        "# Current_status +\n"
        "# pos_current   status\n"
        "0x00040000     +\n"
        "# current_pass   current_status\n"
        "1               +\n"
        "#  pos        size        status\n"
        "0x00000000  0x00010000  +\n"
        "0x00010000  0x00002000  -\n"
        "0x00012000  0x0000E000  ?\n"
        "0x00020000  0x00010000  *\n"
        "0x00030000  0x00010000  /\n"
    )

    def test_parse_sample_mapfile(self):
        mf = DdrescueMapfile.parse_mapfile(self.SAMPLE_MAPFILE_TEXT)
        assert mf.current_pos == 0x40000
        assert mf.current_status == MapBlockStatus.FINISHED
        assert mf.current_pass == 1
        assert len(mf.blocks) == 5

        assert mf.blocks[0].pos == 0x0
        assert mf.blocks[0].size == 0x10000
        assert mf.blocks[0].status == MapBlockStatus.FINISHED

        assert mf.blocks[1].pos == 0x10000
        assert mf.blocks[1].size == 0x2000
        assert mf.blocks[1].status == MapBlockStatus.BAD_SECTOR

        assert mf.blocks[2].status == MapBlockStatus.NON_TRIED
        assert mf.blocks[3].status == MapBlockStatus.NON_TRIMMED
        assert mf.blocks[4].status == MapBlockStatus.NON_SCRAPED

    def test_summary_stats(self):
        mf = DdrescueMapfile.parse_mapfile(self.SAMPLE_MAPFILE_TEXT)
        stats = mf.summary_stats()
        assert stats["rescued_bytes"] == 0x10000
        assert stats["bad_bytes"] == 0x2000
        assert stats["non_tried_bytes"] == 0xE000
        assert stats["non_trimmed_bytes"] == 0x10000
        assert stats["non_scraped_bytes"] == 0x10000
        assert stats["total_bytes"] == 0x40000
        assert stats["is_complete"] is False
        assert len(stats["sha256"]) == 64

    def test_serialization_roundtrip(self):
        mf1 = DdrescueMapfile.parse_mapfile(self.SAMPLE_MAPFILE_TEXT)
        serialized = mf1.to_mapfile_text()
        mf2 = DdrescueMapfile.parse_mapfile(serialized)
        assert mf1.current_pos == mf2.current_pos
        assert mf1.current_pass == mf2.current_pass
        assert len(mf1.blocks) == len(mf2.blocks)
        for b1, b2 in zip(mf1.blocks, mf2.blocks):
            assert b1.pos == b2.pos
            assert b1.size == b2.size
            assert b1.status == b2.status

    def test_initial_mapfile_creation(self):
        mf = DdrescueMapfile.create_initial(total_size=131072, block_size=65536)
        assert len(mf.blocks) == 2
        assert mf.blocks[0].pos == 0
        assert mf.blocks[0].size == 65536
        assert mf.blocks[0].status == MapBlockStatus.NON_TRIED
        assert mf.blocks[1].pos == 65536
        assert mf.blocks[1].size == 65536
        assert mf.blocks[1].status == MapBlockStatus.NON_TRIED
        assert mf.non_tried_bytes == 131072
        assert mf.rescued_bytes == 0

    def test_mapfile_merge_priority(self):
        # Pass 1: Entire disk non-tried except first chunk rescued
        mf1 = DdrescueMapfile(
            current_pos=0x10000,
            current_pass=1,
            blocks=[
                MapfileBlock(pos=0, size=0x10000, status=MapBlockStatus.FINISHED),
                MapfileBlock(pos=0x10000, size=0x10000, status=MapBlockStatus.NON_TRIED),
            ]
        )
        # Pass 2: Second chunk has bad sector in middle
        mf2 = DdrescueMapfile(
            current_pos=0x20000,
            current_pass=2,
            blocks=[
                MapfileBlock(pos=0, size=0x10000, status=MapBlockStatus.FINISHED),
                MapfileBlock(pos=0x10000, size=0x4000, status=MapBlockStatus.FINISHED),
                MapfileBlock(pos=0x14000, size=0x2000, status=MapBlockStatus.BAD_SECTOR),
                MapfileBlock(pos=0x16000, size=0xA000, status=MapBlockStatus.FINISHED),
            ]
        )
        merged = mf1.merge(mf2)
        assert merged.current_pass == 2
        assert merged.rescued_bytes == (0x10000 + 0x4000 + 0xA000)
        assert merged.bad_bytes == 0x2000
        assert merged.non_tried_bytes == 0
        assert merged.is_complete is True

    def test_mapfile_integrity_validation(self):
        # Valid mapfile
        valid_mf = DdrescueMapfile(
            blocks=[
                MapfileBlock(pos=0, size=100, status=MapBlockStatus.FINISHED),
                MapfileBlock(pos=100, size=200, status=MapBlockStatus.BAD_SECTOR),
            ]
        )
        assert valid_mf.validate_integrity() == []

        # Overlapping mapfile
        overlap_mf = DdrescueMapfile(
            blocks=[
                MapfileBlock(pos=0, size=100, status=MapBlockStatus.FINISHED),
                MapfileBlock(pos=80, size=200, status=MapBlockStatus.BAD_SECTOR),
            ]
        )
        issues = overlap_mf.validate_integrity()
        assert len(issues) == 1
        assert "overlaps" in issues[0]


class TestDirectDamagedMediaImager:
    """Validate streaming sector imager, bad sector skipping, and source immutability."""

    def test_direct_imaging_with_bad_sectors(self, tmp_path):
        source_data = b"HEADER_SECTOR_" + b"A" * 498 + b"BAD_SECTOR_DATA" + b"B" * 497 + b"TRAILER_SECTOR" + b"C" * 498
        assert len(source_data) == 512 * 3

        out_img = tmp_path / "salvaged.raw"
        out_map = tmp_path / "salvaged.map"

        # Mark sector 1 (middle sector) as bad
        res = DirectDamagedMediaImager.image_source(
            source_data=source_data,
            output_image_path=out_img,
            mapfile_path=out_map,
            sector_size=512,
            bad_sector_ranges=[(1, 1)],
            chunk_size=512,
        )

        assert res["total_bytes"] == 1536
        assert res["rescued_bytes"] == 1024
        assert res["bad_bytes"] == 512
        assert out_img.is_file()
        assert out_map.is_file()

        # Read back salvaged raw image
        raw_out = out_img.read_bytes()
        assert len(raw_out) == 1536
        assert raw_out[:512] == source_data[:512]  # First sector intact
        assert raw_out[512:1024] == b"\x00" * 512  # Bad sector zero-filled
        assert raw_out[1024:] == source_data[1024:]  # Third sector intact

        # Verify parsed mapfile
        mf = DdrescueMapfile.parse_mapfile(out_map)
        assert mf.rescued_bytes == 1024
        assert mf.bad_bytes == 512

    def test_source_immutability(self, tmp_path):
        source_path = tmp_path / "source.raw"
        original_bytes = b"ORIGINAL_DATA_BLOCK_" * 100
        source_path.write_bytes(original_bytes)
        orig_sha256 = hashlib.sha256(original_bytes).hexdigest()

        out_img = tmp_path / "out.raw"
        out_map = tmp_path / "out.map"

        DirectDamagedMediaImager.image_source(
            source_data=source_path,
            output_image_path=out_img,
            mapfile_path=out_map,
            sector_size=512,
            bad_sector_ranges=[(2, 1)],
        )

        # Confirm source file has NOT been modified
        assert source_path.read_bytes() == original_bytes
        assert hashlib.sha256(source_path.read_bytes()).hexdigest() == orig_sha256


class TestDdrescueCLIAdapter:
    """Validate external CLI command construction and stdout parser."""

    def test_build_ddrescue_command(self):
        cmd = build_ddrescue_command(
            ddrescue_exe=Path("C:/bin/ddrescue.exe"),
            source="\\\\.\\PhysicalDrive3",
            destination="D:/images/drive3.raw",
            mapfile="D:/images/drive3.map",
            sector_size=4096,
            retry_passes=3,
            no_scrape=True,
            direct_access=True,
        )
        assert cmd[0] == "C:\\bin\\ddrescue.exe"
        assert "-b" in cmd and "4096" in cmd
        assert "-r" in cmd and "3" in cmd
        assert "-n" in cmd
        assert "-d" in cmd
        assert cmd[-3] == "\\\\.\\PhysicalDrive3"
        assert cmd[-2] == "D:/images/drive3.raw"
        assert cmd[-1] == "D:/images/drive3.map"

    def test_parse_ddrescue_output(self):
        sample_output = """
        GNU ddrescue 1.28
        Press Ctrl-C to interrupt
        Initial status (read from mapfile)
        rescued: 500 MB, errsize: 0 B, current rate: 25 MB/s
        ipos: 500 MB, opos: 500 MB, pct rescued: 50.00%
        current_pass: 1, bad areas: 0
        """
        res = parse_ddrescue_output(sample_output)
        assert res["rescued_str"] == "500 MB"
        assert res["pct_rescued"] == 50.0
        assert res["current_pass"] == 1
        assert res["bad_areas"] == 0
